spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/root-service
    username: postgres
    password: postgres
    test-on-borrow: true
    validation-query: "SELECT 1;"
    validation-interval: 15000
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: nc.base.configs.PostgresUuidDialect
        temp:
          use_jdbc_metadata_defaults: false